### ISSUE TITLE
Do we have a plugin for Autocomplete?

### ISSUE THREAD

**Issue by PRDinesh** [jez/vim-as-an-ide#36]

**Comment by jez** [comment]
Not sure what you mean, there are a number of good auto-completion plugins. The quality of them will vary based on what language you're writing. One popular one is [YouCompleteMe]. I also recommend [VimAwesome] for searching for plugins; there are a number of completion-related plugins there.

[YouCompleteMe]: https://valloric.github.io/YouCompleteMe/
[VimAwesome]: http://vimawesome.com/?q=cat%3Acompletion

**Comment by PRDinesh** [comment]
Thank you, I have used YouCompleteMe and it worked fine.  Could you please add YouCompleteMe also in your script,

**Comment by jez** [comment]
That's not really the idea of this repo. In its current form, I have compiled a list of plugins which I think are non-objectionable and vastly improve the editing experience for people new to Vim **for the purpose of instruction**.

Regardless of whether we consider YouCompleteMe to be "objectionable," the point of this repo is to instruct people in how to find, install, and read the documentation for various Vim plugins, at which point they can take control of their own Vim configuration.

Congrats! You now know how to use Vim plugins. Therefore, go forth and make disciples of all ~~nations~~ programmers!
